use core::fmt;
use std::collections::{BTreeMap, BTreeSet};

use crate::{Config, SourceInventory};

#[derive(Debug, Clone, PartialEq, Eq)]
pub struct GeneratedRootModule {
    pub path: String,
    pub contents: String,
    pub roots: Vec<GeneratedRoot>,
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub struct GeneratedRoot {
    pub rust_name: String,
    pub type_path: String,
    pub source_file: String,
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub enum RootModuleError {
    NoExportedRoots,
    DuplicateSourceFile {
        source_file: String,
    },
    DuplicateRootTypePath {
        type_path: String,
        first_source_file: String,
        duplicate_source_file: String,
    },
    UnsupportedRootModulePath {
        root_module_file: String,
    },
    UnsupportedSourcePath {
        source_file: String,
    },
    InvalidModuleSegment {
        source_file: String,
        segment: String,
    },
}

pub fn generate_root_module(
    config: &Config,
    inventories: &[SourceInventory],
) -> Result<GeneratedRootModule, RootModuleError> {
    validate_root_module_path(&config.root_discovery.root_module_file)?;
    let roots = collect_generated_roots(inventories)?;
    let contents = render_root_module_contents(&roots);

    Ok(GeneratedRootModule {
        path: config.root_discovery.root_module_file.clone(),
        contents,
        roots,
    })
}

fn collect_generated_roots(
    inventories: &[SourceInventory],
) -> Result<Vec<GeneratedRoot>, RootModuleError> {
    let mut roots = BTreeMap::<String, GeneratedRoot>::new();
    let mut source_files = BTreeSet::<String>::new();
    for inventory in inventories {
        if !source_files.insert(inventory.source_file.clone()) {
            return Err(RootModuleError::DuplicateSourceFile {
                source_file: inventory.source_file.clone(),
            });
        }
        let module_path = rust_module_path(&inventory.source_file)?;
        for item in inventory.exported_roots() {
            let type_path = root_type_path(&module_path, &item.rust_name);
            if let Some(first) = roots.get(&type_path) {
                return Err(RootModuleError::DuplicateRootTypePath {
                    type_path,
                    first_source_file: first.source_file.clone(),
                    duplicate_source_file: inventory.source_file.clone(),
                });
            }
            roots.insert(
                type_path.clone(),
                GeneratedRoot {
                    rust_name: item.rust_name.clone(),
                    type_path,
                    source_file: inventory.source_file.clone(),
                },
            );
        }
    }

    if roots.is_empty() {
        return Err(RootModuleError::NoExportedRoots);
    }

    Ok(roots.into_values().collect())
}

fn validate_root_module_path(root_module_file: &str) -> Result<(), RootModuleError> {
    let valid = !root_module_file.is_empty()
        && root_module_file.ends_with(".rs")
        && !root_module_file.starts_with('/')
        && !has_windows_drive_prefix(root_module_file)
        && !root_module_file.contains('\\')
        && root_module_file
            .split('/')
            .all(|segment| !matches!(segment, "" | "." | ".."));
    if valid {
        Ok(())
    } else {
        Err(RootModuleError::UnsupportedRootModulePath {
            root_module_file: root_module_file.to_owned(),
        })
    }
}

fn has_windows_drive_prefix(path: &str) -> bool {
    let bytes = path.as_bytes();
    bytes.len() >= 2 && bytes[0].is_ascii_alphabetic() && bytes[1] == b':'
}

fn render_root_module_contents(roots: &[GeneratedRoot]) -> String {
    let mut contents = String::new();
    contents.push_str("// @generated by dto_bindgen\n");
    contents.push_str("// Do not edit by hand.\n\n");
    contents.push_str(
        "pub fn dto_bindgen_roots() -> ::std::vec::Vec<::dto_bindgen::export::RootDescriptor> {\n",
    );
    contents.push_str("    ::std::vec![\n");
    for root in roots {
        contents.push_str("        ::dto_bindgen::export::RootDescriptor::new::<");
        contents.push_str(&root.type_path);
        contents.push_str(">(),\n");
    }
    contents.push_str("    ]\n");
    contents.push_str("}\n");
    contents
}

fn root_type_path(module_path: &[String], rust_name: &str) -> String {
    if module_path.is_empty() {
        format!("crate::{rust_name}")
    } else {
        format!("crate::{}::{rust_name}", module_path.join("::"))
    }
}

fn rust_module_path(source_file: &str) -> Result<Vec<String>, RootModuleError> {
    let source_relative = source_relative_path(source_file).ok_or_else(|| {
        RootModuleError::UnsupportedSourcePath {
            source_file: source_file.to_owned(),
        }
    })?;
    let Some(without_ext) = source_relative.strip_suffix(".rs") else {
        return Err(RootModuleError::UnsupportedSourcePath {
            source_file: source_file.to_owned(),
        });
    };

    let mut segments = without_ext
        .split('/')
        .map(str::to_owned)
        .collect::<Vec<_>>();
    match segments.last().map(String::as_str) {
        Some("lib" | "main") => {
            segments.pop();
        }
        Some("mod") => {
            segments.pop();
        }
        Some(_) => {}
        None => {
            return Err(RootModuleError::UnsupportedSourcePath {
                source_file: source_file.to_owned(),
            });
        }
    }

    for segment in &segments {
        if !is_valid_module_segment(segment) {
            return Err(RootModuleError::InvalidModuleSegment {
                source_file: source_file.to_owned(),
                segment: segment.clone(),
            });
        }
    }

    Ok(segments)
}

fn source_relative_path(source_file: &str) -> Option<&str> {
    source_file
        .strip_prefix("src/")
        .or_else(|| source_file.split_once("/src/").map(|(_, path)| path))
}

fn is_valid_module_segment(segment: &str) -> bool {
    let mut chars = segment.chars();
    let Some(first) = chars.next() else {
        return false;
    };
    (first == '_' || first.is_ascii_alphabetic())
        && chars.all(|ch| ch == '_' || ch.is_ascii_alphanumeric())
        && !is_rust_keyword(segment)
}

fn is_rust_keyword(segment: &str) -> bool {
    matches!(
        segment,
        "as" | "async"
            | "await"
            | "break"
            | "const"
            | "continue"
            | "crate"
            | "dyn"
            | "else"
            | "enum"
            | "extern"
            | "false"
            | "fn"
            | "for"
            | "if"
            | "impl"
            | "in"
            | "let"
            | "loop"
            | "match"
            | "mod"
            | "move"
            | "mut"
            | "pub"
            | "ref"
            | "return"
            | "self"
            | "Self"
            | "static"
            | "struct"
            | "super"
            | "trait"
            | "true"
            | "type"
            | "unsafe"
            | "use"
            | "where"
            | "while"
            | "abstract"
            | "become"
            | "box"
            | "do"
            | "final"
            | "macro"
            | "override"
            | "priv"
            | "try"
            | "typeof"
            | "unsized"
            | "virtual"
            | "yield"
            | "gen"
    )
}

impl fmt::Display for RootModuleError {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        match self {
            Self::NoExportedRoots => f.write_str("source manifest did not contain any dto roots"),
            Self::DuplicateSourceFile { source_file } => write!(
                f,
                "source file `{source_file}` appears more than once in root manifest"
            ),
            Self::DuplicateRootTypePath {
                type_path,
                first_source_file,
                duplicate_source_file,
            } => write!(
                f,
                "root type path `{type_path}` is exported from both `{first_source_file}` and `{duplicate_source_file}`"
            ),
            Self::UnsupportedRootModulePath { root_module_file } => write!(
                f,
                "root module file `{root_module_file}` must be a relative .rs path"
            ),
            Self::UnsupportedSourcePath { source_file } => write!(
                f,
                "source file `{source_file}` cannot be mapped to a Rust module path"
            ),
            Self::InvalidModuleSegment {
                source_file,
                segment,
            } => write!(
                f,
                "source file `{source_file}` contains invalid Rust module segment `{segment}`"
            ),
        }
    }
}

impl std::error::Error for RootModuleError {}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::{Config, RootDiscoveryMode, scan_rust_source};

    fn config() -> Config {
        let mut config = Config::default();
        config.root_discovery.mode = RootDiscoveryMode::SourceManifest;
        config.root_discovery.source_files = vec!["src/lib.rs".to_owned()];
        config.root_discovery.root_module_file = "src/generated/dto_roots.rs".to_owned();
        config
    }

    #[test]
    fn generates_root_module_from_exported_source_items() {
        let inventory = scan_rust_source(
            "src/events/user.rs",
            r#"
            #[derive(Dto)]
            #[dto(export)]
            struct UserProfile {
                id: String,
            }

            #[derive(Dto)]
            struct InternalUserState {
                id: String,
            }

            #[derive(Dto)]
            #[dto(export)]
            enum UserEvent {
                Created { profile: UserProfile },
                Deleted,
            }
            "#,
        )
        .unwrap();

        let module = generate_root_module(&config(), &[inventory]).unwrap();

        assert_eq!(module.path, "src/generated/dto_roots.rs");
        assert_eq!(
            module
                .roots
                .iter()
                .map(|root| root.type_path.as_str())
                .collect::<Vec<_>>(),
            [
                "crate::events::user::UserEvent",
                "crate::events::user::UserProfile"
            ]
        );
        assert!(module.contents.contains(
            "::dto_bindgen::export::RootDescriptor::new::<crate::events::user::UserEvent>()"
        ));
        assert!(!module.contents.contains("InternalUserState"));
    }

    #[test]
    fn maps_workspace_relative_source_files_to_crate_paths() {
        let inventory = scan_rust_source(
            "crates/radroots_core/src/money/mod.rs",
            r#"
            #[derive(Dto)]
            #[dto(export)]
            struct RadrootsCoreMoney {
                amount: String,
            }
            "#,
        )
        .unwrap();

        let module = generate_root_module(&config(), &[inventory]).unwrap();

        assert_eq!(module.roots[0].type_path, "crate::money::RadrootsCoreMoney");
    }

    #[test]
    fn rejects_invalid_root_module_paths() {
        let inventory = scan_rust_source(
            "src/sdk.rs",
            r#"
            #[derive(Dto)]
            #[dto(export)]
            struct UserProfile {
                id: String,
            }
            "#,
        )
        .unwrap();
        for root_module_file in [
            "src/generated/dto_roots.txt",
            "/tmp/dto_roots.rs",
            "../dto_roots.rs",
            "src\\generated\\dto_roots.rs",
            "C:/dto_roots.rs",
        ] {
            let mut config = config();
            config.root_discovery.root_module_file = root_module_file.to_owned();

            let err = generate_root_module(&config, &[inventory.clone()]).unwrap_err();

            assert_eq!(
                err,
                RootModuleError::UnsupportedRootModulePath {
                    root_module_file: root_module_file.to_owned()
                }
            );
        }
    }

    #[test]
    fn rejects_duplicate_source_files() {
        let inventory = scan_rust_source(
            "src/sdk.rs",
            r#"
            #[derive(Dto)]
            #[dto(export)]
            struct UserProfile {
                id: String,
            }
            "#,
        )
        .unwrap();

        let err = generate_root_module(&config(), &[inventory.clone(), inventory]).unwrap_err();

        assert_eq!(
            err,
            RootModuleError::DuplicateSourceFile {
                source_file: "src/sdk.rs".to_owned()
            }
        );
    }

    #[test]
    fn rejects_duplicate_generated_type_paths() {
        let first = scan_rust_source(
            "src/user.rs",
            r#"
            #[derive(Dto)]
            #[dto(export)]
            struct User {
                id: String,
            }
            "#,
        )
        .unwrap();
        let duplicate = scan_rust_source(
            "src/user/mod.rs",
            r#"
            #[derive(Dto)]
            #[dto(export)]
            struct User {
                id: String,
            }
            "#,
        )
        .unwrap();

        let err = generate_root_module(&config(), &[first, duplicate]).unwrap_err();

        assert_eq!(
            err,
            RootModuleError::DuplicateRootTypePath {
                type_path: "crate::user::User".to_owned(),
                first_source_file: "src/user.rs".to_owned(),
                duplicate_source_file: "src/user/mod.rs".to_owned(),
            }
        );
    }

    #[test]
    fn rejects_keyword_module_segments() {
        let inventory = scan_rust_source(
            "src/type.rs",
            r#"
            #[derive(Dto)]
            #[dto(export)]
            struct KeywordPath {
                id: String,
            }
            "#,
        )
        .unwrap();

        let err = generate_root_module(&config(), &[inventory]).unwrap_err();

        assert_eq!(
            err,
            RootModuleError::InvalidModuleSegment {
                source_file: "src/type.rs".to_owned(),
                segment: "type".to_owned()
            }
        );
    }

    #[test]
    fn rejects_non_rust_source_paths() {
        let inventory = scan_rust_source(
            "src/sdk.txt",
            r#"
            #[derive(Dto)]
            #[dto(export)]
            struct UserProfile {
                id: String,
            }
            "#,
        )
        .unwrap();

        let err = generate_root_module(&config(), &[inventory]).unwrap_err();

        assert_eq!(
            err,
            RootModuleError::UnsupportedSourcePath {
                source_file: "src/sdk.txt".to_owned()
            }
        );
    }

    #[test]
    fn rejects_source_manifests_without_exported_roots() {
        let inventory = scan_rust_source(
            "src/internal.rs",
            r#"
            #[derive(Dto)]
            struct InternalOnly {
                id: String,
            }
            "#,
        )
        .unwrap();

        let err = generate_root_module(&config(), &[inventory]).unwrap_err();

        assert_eq!(err, RootModuleError::NoExportedRoots);
    }
}
