use core::fmt;
use std::collections::BTreeMap;

use crate::{Config, SourceInventory};

#[derive(Debug, Clone, PartialEq, Eq)]
pub struct GeneratedRootModule {
    pub path: String,
    pub contents: String,
    pub roots: Vec<GeneratedRoot>,
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub struct GeneratedRoot {
    pub rust_name: String,
    pub type_path: String,
    pub source_file: String,
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub enum RootModuleError {
    NoExportedRoots,
    UnsupportedSourcePath {
        source_file: String,
    },
    InvalidModuleSegment {
        source_file: String,
        segment: String,
    },
}

pub fn generate_root_module(
    config: &Config,
    inventories: &[SourceInventory],
) -> Result<GeneratedRootModule, RootModuleError> {
    let roots = collect_generated_roots(inventories)?;
    let contents = render_root_module_contents(&roots);

    Ok(GeneratedRootModule {
        path: config.root_discovery.root_module_file.clone(),
        contents,
        roots,
    })
}

fn collect_generated_roots(
    inventories: &[SourceInventory],
) -> Result<Vec<GeneratedRoot>, RootModuleError> {
    let mut roots = BTreeMap::<String, GeneratedRoot>::new();
    for inventory in inventories {
        let module_path = rust_module_path(&inventory.source_file)?;
        for item in inventory.exported_roots() {
            let type_path = root_type_path(&module_path, &item.rust_name);
            roots
                .entry(type_path.clone())
                .or_insert_with(|| GeneratedRoot {
                    rust_name: item.rust_name.clone(),
                    type_path,
                    source_file: inventory.source_file.clone(),
                });
        }
    }

    if roots.is_empty() {
        return Err(RootModuleError::NoExportedRoots);
    }

    Ok(roots.into_values().collect())
}

fn render_root_module_contents(roots: &[GeneratedRoot]) -> String {
    let mut contents = String::new();
    contents.push_str("// @generated by dto_bindgen\n");
    contents.push_str("// Do not edit by hand.\n\n");
    contents.push_str(
        "pub fn dto_bindgen_roots() -> ::std::vec::Vec<::dto_bindgen::export::RootDescriptor> {\n",
    );
    contents.push_str("    ::std::vec![\n");
    for root in roots {
        contents.push_str("        ::dto_bindgen::export::RootDescriptor::new::<");
        contents.push_str(&root.type_path);
        contents.push_str(">(),\n");
    }
    contents.push_str("    ]\n");
    contents.push_str("}\n");
    contents
}

fn root_type_path(module_path: &[String], rust_name: &str) -> String {
    if module_path.is_empty() {
        format!("crate::{rust_name}")
    } else {
        format!("crate::{}::{rust_name}", module_path.join("::"))
    }
}

fn rust_module_path(source_file: &str) -> Result<Vec<String>, RootModuleError> {
    let source_relative = source_relative_path(source_file).ok_or_else(|| {
        RootModuleError::UnsupportedSourcePath {
            source_file: source_file.to_owned(),
        }
    })?;
    let Some(without_ext) = source_relative.strip_suffix(".rs") else {
        return Err(RootModuleError::UnsupportedSourcePath {
            source_file: source_file.to_owned(),
        });
    };

    let mut segments = without_ext
        .split('/')
        .map(str::to_owned)
        .collect::<Vec<_>>();
    match segments.last().map(String::as_str) {
        Some("lib" | "main") => {
            segments.pop();
        }
        Some("mod") => {
            segments.pop();
        }
        Some(_) => {}
        None => {
            return Err(RootModuleError::UnsupportedSourcePath {
                source_file: source_file.to_owned(),
            });
        }
    }

    for segment in &segments {
        if !is_valid_module_segment(segment) {
            return Err(RootModuleError::InvalidModuleSegment {
                source_file: source_file.to_owned(),
                segment: segment.clone(),
            });
        }
    }

    Ok(segments)
}

fn source_relative_path(source_file: &str) -> Option<&str> {
    source_file
        .strip_prefix("src/")
        .or_else(|| source_file.split_once("/src/").map(|(_, path)| path))
}

fn is_valid_module_segment(segment: &str) -> bool {
    let mut chars = segment.chars();
    let Some(first) = chars.next() else {
        return false;
    };
    (first == '_' || first.is_ascii_alphabetic())
        && chars.all(|ch| ch == '_' || ch.is_ascii_alphanumeric())
}

impl fmt::Display for RootModuleError {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        match self {
            Self::NoExportedRoots => f.write_str("source manifest did not contain any dto roots"),
            Self::UnsupportedSourcePath { source_file } => write!(
                f,
                "source file `{source_file}` cannot be mapped to a Rust module path"
            ),
            Self::InvalidModuleSegment {
                source_file,
                segment,
            } => write!(
                f,
                "source file `{source_file}` contains invalid Rust module segment `{segment}`"
            ),
        }
    }
}

impl std::error::Error for RootModuleError {}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::{Config, RootDiscoveryMode, scan_rust_source};

    fn config() -> Config {
        let mut config = Config::default();
        config.root_discovery.mode = RootDiscoveryMode::SourceManifest;
        config.root_discovery.source_files = vec!["src/lib.rs".to_owned()];
        config.root_discovery.root_module_file = "src/generated/dto_roots.rs".to_owned();
        config
    }

    #[test]
    fn generates_root_module_from_exported_source_items() {
        let inventory = scan_rust_source(
            "src/events/user.rs",
            r#"
            #[derive(Dto)]
            #[dto(export)]
            struct UserProfile {
                id: String,
            }

            #[derive(Dto)]
            struct InternalUserState {
                id: String,
            }

            #[derive(Dto)]
            #[dto(export)]
            enum UserEvent {
                Created { profile: UserProfile },
                Deleted,
            }
            "#,
        )
        .unwrap();

        let module = generate_root_module(&config(), &[inventory]).unwrap();

        assert_eq!(module.path, "src/generated/dto_roots.rs");
        assert_eq!(
            module
                .roots
                .iter()
                .map(|root| root.type_path.as_str())
                .collect::<Vec<_>>(),
            [
                "crate::events::user::UserEvent",
                "crate::events::user::UserProfile"
            ]
        );
        assert!(module.contents.contains(
            "::dto_bindgen::export::RootDescriptor::new::<crate::events::user::UserEvent>()"
        ));
        assert!(!module.contents.contains("InternalUserState"));
    }

    #[test]
    fn maps_workspace_relative_source_files_to_crate_paths() {
        let inventory = scan_rust_source(
            "crates/radroots_core/src/money/mod.rs",
            r#"
            #[derive(Dto)]
            #[dto(export)]
            struct RadrootsCoreMoney {
                amount: String,
            }
            "#,
        )
        .unwrap();

        let module = generate_root_module(&config(), &[inventory]).unwrap();

        assert_eq!(module.roots[0].type_path, "crate::money::RadrootsCoreMoney");
    }

    #[test]
    fn rejects_source_manifests_without_exported_roots() {
        let inventory = scan_rust_source(
            "src/internal.rs",
            r#"
            #[derive(Dto)]
            struct InternalOnly {
                id: String,
            }
            "#,
        )
        .unwrap();

        let err = generate_root_module(&config(), &[inventory]).unwrap_err();

        assert_eq!(err, RootModuleError::NoExportedRoots);
    }
}
